import type { Metadata } from "next";
import { unbounded, golosText } from "@/assets/fonts/fonts";
import "@/assets/styles/globals.css";

import Menu from "@/components/sections/Menu";
import Footer from "@/components/sections/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${unbounded.variable} ${golosText.variable} antialiased font-golos-text text-foreground`}
      >
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
